### model
model: MLP # currently supported: MLP # TODO: implement transformer, etc

### dataset
meta_dataset: openml-cc18 # openml-cc18, tableshift, openml-regression
# currently available dataset list
# openml-cc18: adult(income), cmc, mfeat-karhunen(karhunen), optdigits, diabetes, semeion, mfeat-pixel, dna
# tableshift (for classification): acsincome, acsfoodstamps, acspubcov, acsunemployment, brfss_diabetes, brfss_blood_pressure, communities_and_crime, compas, diabetes_readmission, german, nhanes_cholesterol, nhanes_lead, physionet, anes, heloc, mimic_extract_los_3, mimic_extract_mort_hosp, mooc
dataset: cmc
shift_type: column_drop # null, natural, Gaussian, random_drop, column_drop, column_block_drop, mean_shift, std_shift, mean_std_shift
shift_severity: 0.3
normalizer: StandardScaler
imputation_method: emd # zero, mean, emd(empirical marginal distribution)

### hyperparameters for training
epochs: 50
train_batch_size: 64
train_optimizer: AdamW
train_lr: 1e-3

### hyperparameters for test-time adaptation
episodic: false # reset model to the pretrained one for every batch if true
num_steps: 1 # optimization steps for every batch
test_batch_size: 64
test_optimizer: AdamW
test_lr: 1e-4
# train_params: [all] TODO: implement train_params
# TODO: implement learning rate scheduler

##################################################################
### methods & other hyperparameters
method: [sar] # TODO: implement various methods # em, sar

temp: 1 # temperature scaling
##################################################################

### device
device: cuda

### seed for reproductiblity
seed: 42

##################################################################
### output dir for saving model
out_dir: exps/cmc_new

### logging
log_dir: log

### wandb
wandb_user: drumpt

### slack_notification
slack_token: xoxb-5074113602964-5068716983253-VPOnZMWgclHFEjqLVgW4KlYd
slack_channel: experiment
##################################################################