### model
model: MLP # currently supported: MLP # TODO: implement transformer, etc

### dataset
meta_dataset: tableshift # openml-cc18, tableshift, openml-regression, shifts
## currently available dataset list
# openml-cc18: adult(income), cmc, mfeat-karhunen(karhunen), optdigits, diabetes, semeion, mfeat-pixel, dna
# tableshift: diabetes_readmission(O), heloc(O), acsincome, acsfoodstamps(X), acspubcov(X), acsunemployment(X), brfss_diabetes, brfss_blood_pressure(X), communities_and_crime(X), compas(X/test를 써야함), german(X/test를 써야함), nhanes_cholesterol(X), nhanes_lead(X), physionet, anes(X), mimic_extract_los_3, mimic_extract_mort_hosp, mooc
# openml-regression: abalone, cholestrol
dataset: heloc
shift_type: mean_std_shift # for synthetic shift: null, Gaussian, random_drop, column_drop, column_block_drop, mean_shift, std_shift, mean_std_shift
shift_severity: 0.6
normalizer: StandardScaler
imputation_method: emd # zero, mean, emd(empirical marginal distribution)

### hyperparameters for MAE pretraining
pretrain_epochs: 20
pretrain_batch_size: 64
pretrain_optimizer: AdamW
pretrain_lr: 1e-4
mask_ratio: 0.75
mixup: null # input, feature, null
mixup_scale: 3
train_ratio: 1.0
no_mask: false
tt_imputation_method: emd

### hyperparameters for training
retrain: true
epochs: 50
train_batch_size: 64
train_optimizer: AdamW
train_lr: 1e-4
test_mask_ratio: 0.75

### hyperparameters for test-time adaptation
episodic: false # reset model to the pretrained one for each batch if true
num_steps: 10 # optimization steps for each batch
test_batch_size: 64
test_optimizer: AdamW
test_lr: 1e-6
train_params: [all] # currently supported: all, LN, BN, GN
# TODO: implement learning rate scheduler

##################################################################
### methods & other hyperparameters
method: [sar] # currently supported: sar, em, gem, ns, kld, dm
temp: 1 # temperature scaling
renyi_entropy_alpha: 1.5
ns_threshold: 0.04 # negative sampling
kld_weight: 0.1
dm_weight: 0.1
##################################################################

### device
device: cuda

### seed for reproduciblity
seed: 3

##################################################################
### log dir for logging
log_dir: log_final_wepisodic

### output dir for saving model
out_dir: exps/test_mae

### tsne
tsne: false
tsne_dir: tsne

### wandb
wandb_user: drumpt

### memo
memo_aug_num: 64
no_mae_based_imputation: false

log_prefix: log_final

### slack_notification
slack_token: xoxb-5074113602964-5068716983253-VPOnZMWgclHFEjqLVgW4KlYd
slack_channel: experiment
##################################################################